apiVersion: v1
kind: Service
metadata:
  name: tezca-api
  labels:
    app.kubernetes.io/name: tezca-api
    app.kubernetes.io/part-of: tezca
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tezca-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
