apiVersion: v1
kind: Service
metadata:
  name: tezca-web
  labels:
    app.kubernetes.io/name: tezca-web
    app.kubernetes.io/part-of: tezca
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tezca-web
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
