apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tezca-redis-data
  labels:
    app.kubernetes.io/name: tezca-redis
    app.kubernetes.io/part-of: tezca
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
