apiVersion: v1
kind: Service
metadata:
  name: tezca-admin
  labels:
    app.kubernetes.io/name: tezca-admin
    app.kubernetes.io/part-of: tezca
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tezca-admin
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
