apiVersion: v1
kind: Service
metadata:
  name: tezca-es
  labels:
    app.kubernetes.io/name: tezca-es
    app.kubernetes.io/part-of: tezca
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tezca-es
  ports:
    - port: 9200
      targetPort: 9200
      protocol: TCP
